# -*- coding: utf-8 -*-
"""EDA_Solar_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IXDh2PuVXSOnnMatJ9zZwaiiT3CNrSwF
"""

from google.colab import drive
drive.mount('/content/drive')

cd /content/drive/MyDrive/Capstone/data

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Загрузка данных
weather = pd.read_csv("Weather_Data_reordered_all.csv")
solar = pd.read_csv("Solar_Energy_Generation.csv")
sites = pd.read_csv("Solar_Site_Details.csv")

print("Weather columns:", weather.columns.tolist())
print("Solar columns:", solar.columns.tolist())

weather["Timestamp"] = pd.to_datetime(weather["Timestamp"])
solar["Timestamp"] = pd.to_datetime(solar["Timestamp"])

df = pd.merge(solar, weather, on=["CampusKey", "Timestamp"], how="inner")
df = pd.merge(df, sites, on=["CampusKey", "SiteKey"], how="left")
df.dropna(inplace=True)

df["hour"] = df["Timestamp"].dt.hour
df["month"] = df["Timestamp"].dt.month

df = df.sort_values("Timestamp")
df["gen_ma_3h"] = df.groupby("SiteKey")["SolarGeneration"] \
                    .transform(lambda x: x.shift(1).rolling(window=3, min_periods=1).mean())

df.to_csv("processed_solar_data.csv", index=False)
print("Данные сохранены в processed_solar_data.csv")

# Визуализация: генерация по часам
sns.lineplot(data=df, x="hour", y="SolarGeneration", ci="sd")
plt.title("Средняя генерация по часам суток")
plt.xlabel("Час")
plt.ylabel("Генерация энергии")
plt.show()

# Визуализация: генерация по месяцам
sns.boxplot(data=df, x="month", y="SolarGeneration")
plt.title("Генерация энергии по месяцам")
plt.xlabel("Месяц")
plt.ylabel("Генерация")
plt.show()

features = ["AirTemperature", "RelativeHumidity", "WindSpeed", "kWp", "SolarGeneration"]
corr = df[features].corr()
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("Корреляция признаков с генерацией")
plt.show()